config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'reports#index'

  resources :reports, only: :index

  resources :reports, only: :show do
    get 'stats', to: 'reports#stats'
    get 'filtered', to: 'reports#filtered'
    get 'filtered_ee', to: 'reports#filtered_ee'
    get 'filtered_ei', to: 'reports#filtered_ei'
  end

  scope module: :reports do
    get 'download_committee_ei', to: 'downloads#download_committee_ei', param: :report_id
    get 'download_committee_ee', to: 'downloads#download_committee_ee', param: :report_id
  end

end

app/models/hearing.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: hearings
#
#  id                 :bigint           not null, primary key
#  clics_m_id_digest  :string
#  hearing_item_uuids :string           default([]), is an Array
#  meeting_date       :string
#  meeting_time       :string
#  meeting_uid        :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#
class Hearing < ApplicationRecord
  has_many :committee_hearings
  has_many :committees, through: :committee_hearings
  has_many :hearing_items
  has_many :hearing_error_items, through: :hearing_items
  has_many :error_items, through: :hearing_error_items

  # Note that CLICS will reuse a meeting for multiple committees even if it is
  # defined by a single committee's uid. Example: The last meeting_uid is valid
  # because it was some kind of joint meeting
  # {
  #   "committee_name": "H_PBH_2021A",
  #   "meeting_dates": [
  #   "2021-01-22T10:22:48Z",
  #   "2021-02-16T13:31:40Z",
  #   "2021-02-26T11:30:00Z"
  #   ],
  #   "meeting_uids": [
  #   "H_PBH_2021A_20210122_102248",
  #   "H_PBH_2021A_20210216_133140",
  #   "H_HI_2021A_20210226_114102"   <--- THIS ONE IS JOINT
  #   ]
  # }
  # Therefore we cannot validate uniqueness of meeting_uid or digest
  validates :clics_m_id_digest, :meeting_uid, presence: true
end

app/models/reports/committee_report.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: reports
#
#  id         :bigint           not null, primary key
#  type       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
module Reports
  class CommitteeReport < Reports::Report
    attribute :type, :string, default: 'Reports::CommitteeReport'
    # has_many :early_errors
    # has_many :error_items

    # def early_errors
    #   EarlyError.where(reportable_id: id)
    # end

    # def error_items
    #   ErrorItem.where(reportable_id: id)
    # end
  end
end

app/models/reports/report.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: reports
#
#  id         :bigint           not null, primary key
#  type       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
module Reports
  class Report < ApplicationRecord
    has_many :error_items #, class_name: 'Errors::ErrorItem'
    has_many :early_errors #, class_name: 'Errors::EarlyErrors'
    # def error_items
    #   ErrorItem.where(reportable_id: id)
    # end
  end
end

app/controllers/reports/downloads_controller.rb
# frozen_string_literal: true

module Reports
  class DownloadsController < ApplicationController
    def download_committee_ei
      @report = Reports::Report.find(params[:report_id])
      @csv = Reports::CommitteePagesCsvService.new(@report).call
      handle_download
    end

    def download_committee_ee
      @report = Reports::Report.find(params[:report_id])
      @csv = Reports::CommitteeEarlyErrorCsvService.new(@report).call
      handle_download
    end

    def handle_download
      if @csv.error == true
        msg = 'We hit a snag  writing the CSV report. See logs for details. Error Message: '
        redirect_to report_path(id: @report.id), alert: msg and return
      end

      respond_to do |format|
        format.csv do
          send_file(@csv.file_path,
                    filename: File.basename(@csv.file_name),
                    type: 'text/csv',
                    disposition: 'attachment')
        rescue StandardError => e
          msg = "We hit a snag  writing the CSV report. Error: #{e}"
          redirect_to report_path(report_id: @report.id, format: :html), alert: msg and return
        end
      end
    end
  end
end

app/controllers/reports_controller.rb
# frozen_string_literal: true

class ReportsController < ApplicationController
  before_action :find_report, except: :index

  def index
    @reports = Reports::Report.all.order(id: :desc).limit(10)
    @recent_report = Reports::Report.all.present? ? Reports::Report.last : nil
  end

  def show
    shared_dash_vars
    dropdown_collections
  end

  def filtered
    shared_dash_vars
    dropdown_collections

    # Save a copy of current filters to pass along to the lazy-loaded
    # views (#stats, #filtered_ee, #filtered_ei)
    @f_params = params_for_filters
  end

  def stats
    # lazy-loaded via hotwire from #show or #filtered
    @stats = ::Filters::Stats.new(@report, params[:f_params]).stats
    @error_hash = DataErrors.enum_errors.invert
  end

  def filtered_ee
    # lazy-loaded via hotwire from #filtered
    if params[:f_params] && params[:f_params][:day_diff].present?
      day_diff = params[:f_params][:day_diff]
      day_diff_errs = ::Filters::DayDiffErrors.new(day_diff, @report, 'early_errors')
      @filtered_early_errors = day_diff_errs.errs
    else
      @filtered_early_errors = ::Filters::RansackEarlyErrors.new(params[:f_params], @report.id).call
    end
    @filtered_early_errors
  end

  def filtered_ei
    # lazy-loaded via hotwire from #filtered
    if params[:f_params] && params[:f_params][:day_diff].present?
      day_diff = params[:f_params][:day_diff]
      day_diff_errs = ::Filters::DayDiffErrors.new(day_diff, @report, 'error_items')
      filtered_ei = day_diff_errs.errs
    else
      filtered_ei = ::Filters::RansackErrorItems.new(params[:f_params], @report.id).call
    end
    @filtered_error_items = ::Filters::ErrorItemsToHash.new(filtered_ei).call
  end

  private

  def find_report
    report_id = params[:report_id] || params[:id]
    @report = Reports::Report.find(report_id)
  end

  def shared_dash_vars
    @recent_report = Reports::Report.last
    @current_page = "Report #{@report.id}" if Reports::Report.last.id != @report.id
    @current_session = Sessions.all.last
    @humanized_filters = ::Filters::HumanizedFilters.humanized_filters(params)
  end

  def dropdown_collections
    @early_sort_errors = DataErrors.early_errors_for_ui
    @comparison_sort_errors = DataErrors.comparison_errors_for_ui
    @sessions = Sessions.all.reverse.collect { |s| [s, s] }.unshift(%w[All nil])
    @committee_origins = [%w[All nil], %w[House house], %w[Senate senate], %w[Conference conference], %w[Joint joint]]
    @committee_ids = Committee.committees_for_filter
  end

  def params_for_filters
    filtered_params = {}
    filtered_params['day_diff'] = params['day_diff']
    filtered_params['early_sort_errors'] = params['early_sort_errors']
    filtered_params['comparison_sort_errors'] = params['comparison_sort_errors']
    filtered_params['sessions'] = params['sessions']
    filtered_params['committee_origins'] = params['committee_origins']
    filtered_params['committee_ids'] = params['committee_ids']
    filtered_params
  end
end

app/views/reports/_filter_by_days.erb
<div class="border border-warning">
  <div class="mx-3 my-2">
    <div class="card-group">


      <div class="card border-none" >
        <div class="card-body p-0 m-0">
          <h4 class="m-0 p-0">View By Daily Differences</h4>
          <small>* Cannot be combined with other Filters</small>
        </div>
      </div>

      <div class="card border-none" >
        <div class="card-group">
          <div class="card border-none" >
            <div class="card-body p-0 m-0">
              <div class="px-3 pt-1" id="filter-1-day">
                <div class='font-0dot75em bold'>Yesterday </div>
                <%= link_to "Filter", report_filtered_path(@report, day_diff: 1), class:"button btn btn-danger btn-sm mx-auto d-block p-0 px-1 m-0"%>
              </div>
            </div>
          </div>
          <div class="card border-none" >
            <div class="card-body p-0 m-0">
              <div class="px-3 pt-1" id="filter-3-day">
                <div class='font-0dot75em bold'>3 Days ago </div>
                <%= link_to "Filter", report_filtered_path(@report, day_diff: 3), class:"button btn btn-sm btn-orange mx-auto d-block p-0 px-1 m-0"%>
              </div>
            </div>
          </div>
          <div class="card border-none" >
            <div class="card-body p-0 m-0">
              <div class="px-3 pt-1" id="filter-5-day">
                <div class='font-0dot75em bold'>5 Days ago </div>
                <%= link_to "Filter", report_filtered_path(@report, day_diff: 5), class:"button btn btn-warning btn-sm mx-auto d-block p-0 px-1 m-0"%>
              </div>
            </div>
          </div>
          <div class="card border-none" >
            <div class="card-body p-0 m-0">
              <div class="px-3 pt-1" id="filter-7-day">
                <div class='font-0dot75em bold'>1 Week ago </div>
                <%= link_to "Filter", report_filtered_path(@report, day_diff: 7), class:"button btn btn-yellow btn-sm mx-auto d-block p-0 px-1 m-0"%>
              </div>
            </div>
          </div>

        </div>
    </div>
    </div>

  </div>
</div>

app/views/reports/_filter_dropdowns.html.erb
<div class="border border-info" id='multi-selection-section'>
  <div class="mx-3 my-2">
    <h4>View By Filtered Results <small style="font-size:0.5em">* Use Shift or Ctrl to select multiple values. Results are a 'union' of any matches per dropdown</small>
    </h4>


    <div
    data-controller="dropdown"
    data-dropdown-comIdList="<%= @committee_ids %>"
    data-dropdown-comIdSelected="<%= selected_ids_with_comm_name(@f_params)%>"
    class=""
    >
      <%= form_with url: report_filtered_path(@report), local: true, method: :get do |f| %>

        <div class="card-group row">

          <div class="col-md">
            <div class="card border-none">
              <div class="card-block">
                <div class="font-0dot75em ">
                  <strong>Early Errors</strong>
                </div>
                <div class="form-group font-0dot75em mb-1">
                  <%= f.select('early_sort_errors', @early_sort_errors, {selected: selected_or_none(@f_params,'early_sort_errors')},  {multiple: true, style: 'width: 100%'}) %>
                </div>
              </div>
            </div>
          </div>

          <div class=" col-md">
            <div class="card border-none ">
              <div class="card-block">
                <div class="font-0dot75em">
                  <strong>Comparison Errors</strong>
                </div>
                <div class="form-group font-0dot75em mb-1">
                  <%= f.select('comparison_sort_errors',
                              @comparison_sort_errors,
                              {selected: selected_or_none(@f_params,'comparison_sort_errors')},
                              {multiple: true, style: 'width: 100%'}
                              ) %>
                </div>
              </div>
            </div>
          </div>

          <div class=" col-md">
            <div class="card border-none ">
              <div class="card-block">
                <div class="font-0dot75em">
                  <strong>Sessions</strong>
                </div>
                <div class="form-group font-0dot75em mb-1">
                  <%= f.select('sessions',
                              @sessions,
                              {selected:  selected_or_current(@f_params, 'sessions', @current_session)},
                              {
                                multiple: true,
                                style: 'width: 100%',
                                data: { 'dropdown-target': "sessionsIds", 'action' => "click->dropdown#updateCommIdList" }
                              }) %>
                </div>
              </div>
            </div>
          </div>

          <div class=" col-md">
            <div class="card border-none ">
              <div class="card-block">
                <div class="font-0dot75em">
                  <strong>Committee Type</strong>
                </div>
                <div class="form-group font-0dot75em mb-1">
                  <%= f.select('committee_origins',
                                @committee_origins,
                                {selected: selected_or_nil(@f_params, 'committee_origins')},
                                {
                                  multiple: true,
                                  style: 'width: 100%',
                                  data: { 'dropdown-target': "originIds", 'action' => "click->dropdown#updateCommIdList" }
                                }) %>
                </div>
              </div>
            </div>
          </div>

          <div class=" col-md">
            <div class="card border-none ">
              <div class="card-block">
                <div class="font-0dot75em">
                  <strong>Committee ID</strong>
                </div>
                <div class="form-group font-0dot75em mb-1">
                  <%= f.select('committee_ids',
                              @committee_ids,
                              {selected: selected_or_nil(@f_params, 'committee_ids')},
                              {
                                multiple: true,
                                style: 'width: 100%',
                                data: { 'dropdown-target': "commIds" }
                              }) %>
                </div>
              </div>
            </div>
          </div>
        </div>


        <div class="form-group font-0dot75em pt-0">
          <%= f.submit "Filter", class:"button btn btn-info btn-sm px-1 py-0 m-0"%>
        <% end %>
        <%= link_to "Reset", report_path(@report),class:"button btn btn-secondary btn-sm px-1 py-0 m-0" %>
        </div>
      </div>
    </div>
  </div>

app/views/reports/_report_date_and_downloads.erb
<div class="border border-success">
  <div class="mx-3 my-2">
    <div class="card-group">


      <div class="card border-none" >
        <div class="card-body p-0 m-0">
          <h4 class="m-0 p-0">Run Date: <%= report_timestamp(@report.created_at)%></h4>
          <strong>Report id : <%= @report.id%> </strong>
        </div>
      </div>

      <div class="card border-none" >
        <div class="card-group">

          <div class="card border-none" >
            <div class="card-body p-0 m-0">
              <% "intentionally blank" %>
            </div>
          </div>

          <div class="card border-none" >
            <div class="card-body p-0 m-0">
              <div class="px-3 pt-1">
                <div class='font-0dot75em bold'> Early Errors </div>
                <%= link_to "Download CSV", download_committee_ee_path(report_id: @report.id, format: :csv), class:"button btn btn-success btn-sm mx-auto d-block p-0 px-1 m-0", "data-confirm" => "This may take up to a minute. Proceed?"%>
              </div>
            </div>
          </div>

          <div class="card border-none" >
            <div class="card-body p-0 m-0">
              <div class="px-3 pt-1">
                <div class='font-0dot75em bold'> Page Comparison Errors </div>
                <%= link_to "Download CSV", download_committee_ei_path(report_id: @report.id, format: :csv), class:"button btn btn-success btn-sm mx-auto d-block p-0 px-1 m-0", "data-confirm" => "This might take a few minutes. Proceed?" %>
              </div>
            </div>
          </div>


        </div>
      </div>
    </div>

  </div>
</div>

app/views/reports/_show_shared.html.erb
<div class='m-1 pt-2'>
    <%= render 'report_date_and_downloads'%>
</div>

<div class='m-1 pt-2'>
  <%= render 'reports/filter_by_days'%>
</div>

<div class='m-1 pt-2'>
  <%= render 'reports/filter_dropdowns'%>
</div>


<hr class="thick-dark-grey"></hr>
<h4>Results</h4>
<div class='m-1'>
  <%= render 'stats_outer'%>
</div>

app/views/reports/_stats_outer.html.erb
<div class="" id="stats-outer-section">

  <div class="">
    <h4>Stats  <small style="font-size:0.5em"> { Current filters: <%= @humanized_filters%> } </small>
    </h4>
  </div>

  <%= turbo_frame_tag("stats-section", src: report_stats_path(report_id: @report.id, f_params: @f_params)) do %>
    <div class="m-2 p-2">
      Loading...
    </div>
    <%= render 'components/spinner' %>
  <%end %>
</div>

app/views/reports/filtered.html.erb
<%= render 'reports/show_shared'%>
<div class='m-1 pt-1'>

  <%= turbo_frame_tag("filtered-early-errors", src: report_filtered_ee_path(report_id: @report.id, f_params: @f_params)) do %>
    <div class='m-1 pt-4'>
      Loading Early Errors ...
    </div>
    <%= render 'components/spinner' %>
  <%end%>


  <%= turbo_frame_tag("filtered-error-items", src: report_filtered_ei_path(report_id: @report.id, f_params: @f_params)) do %>
    <div class='m-1 pt-4'>
      Loading Comparison Errors ...
    </div>
    <%= render 'components/spinner' %>
  <%end%>

</div>

app/views/reports/filtered_ee.html.erb
<%= turbo_frame_tag("filtered-early-errors") do %>

  <% if @filtered_early_errors.present?%>
    <div class='m-1 pt-4'>
      <h4>Early Errors (we hit a snag and couldn't test the Webpages)</h4>
      <table class="table table-bordered font-0dot75em">
        <thead class="">
          <tr>
            <th style="width: 20%">Sortable Error</th>
            <th style="width: 80%">Error Explanation</th>
          </tr>
        </thead>
        <tbody class="cell-break">
          <% @filtered_early_errors.each do |ee|%>
            <tr id=<%="ee-id-#{ee.id}"%>>
              <td> <%= ee.sort_error%></td>
              <td>
                <% truncated_msg(ee.description).each do |row| %>
                <div> <%= row %> </div>
                <%end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  <%end%>
<%end%>

app/views/reports/filtered_ei.html.erb
<%= turbo_frame_tag("filtered-error-items") do %>
  <% if @filtered_error_items.present?%>

    <div class='m-1 pt-4'>
      <h4>Comparison Errors</h4>
      <% @filtered_error_items.each do |all_ei_by_comm|%>
        <% first_comm = all_ei_by_comm[0]%>

        <div class='target-page-results' id=<%= first_comm['clics_committee_id']%>>
          <p class='pt-4 m-0 target-page-url'>
            Target Page:
            <%= link_to first_comm['url_filepath'], cogar_url(first_comm['url_filepath']), class: ""%>
          </p>
        <table class="table table-bordered font-0dot75em mb-4" id=<%= "table-#{first_comm['clics_committee_id']}"%>>
            <thead class="table-info">
              <tr>
                <th style="width:12%">Committee Id</th>
                <th style="width:14%">Meeting Id</th>
                <th style="width:14%">Hearing Item</th>
                <th style="width:8%">Sortable Error</th>
                <th style="width:10%">CLICS key</th>
                <th style="width:14%">CLICS value</th>
                <th style="width:10%">Target CSS</th>
                <th style="width:14%">Target Value</th>
              </tr>
            </thead>
            <tbody class="cell-break" >
              <% all_ei_by_comm.each do |ei|%>
                <% if ei['vote_summary_hi_id'].present? %>
                  <%= render partial: 'reports/error_item_tables/filtered_ei_inner_table_votes', locals: {ei: ei}  %>
                <% else %>
                  <%= render partial: 'reports/error_item_tables/filtered_ei_inner_table', locals:{ei:ei}  %>
                <% end %>
              <% end %>
            </tbody>
          </table>
        <% end %>
        </div>
      </div>

  <%end%>
<%end%>

app/views/reports/index.html.erb
<div class='m-5'>
  <h1>All Reports Page</h1>
  <p> (well, just the most recent ones)</p>
</div>

<div class='m-5'>
<% @reports.each do |report|%>

    <div class="card mb-3" style="max-width: 540px;">
      <div class="row no-gutters">
        <div class="col-md-8">
          <div class="card-body">
            <p class="card-text">
              Report <%= report.id%>
            </p>
            <p class="card-text">
              Date: <%= report_timestamp(report.created_at)%>
            </p>
          </div>
        </div>
        <div class="col-md-4 row my-auto">
          <%= link_to "Go!", report_path(report.id), class:"button btn btn-success mx-auto d-block " %>
        </div>
      </div>
    </div>


<% end %>
</div>

app/views/reports/show.html.erb
<%= render 'reports/show_shared'%>

app/views/reports/stats.html.erb
<div class="m-0 p-0">

  <%= turbo_frame_tag("stats-section") do %>
    <div class="card-group">
      <div class="card border-0">
        <div class="card-body m-0 p-1">
          <table class="table table-bordered table-sm">
            <thead class="table-warning">
              <tr>
                <th class='font-0dot75em'>Error</th>
                <th class='font-0dot75em' style="width:20%">Count</th>
              </tr>
            </thead>
            <tbody class="cell-break">
              <tr id="stats-tic">
                <td class='font-0dot75em'>Total Items checked</td>
                <td class='font-0dot75em'><%=@stats[:stats_total_fields]%></td>
              </tr>
              <tr id="stats-tee">
                <td class='font-0dot75em'>Total Early Errors
                </td>
                <td class='font-0dot75em'><%=@stats[:stats_total_ee_errors]%></td>
              </tr>
              <tr id="stats-tce">
                <td class='font-0dot75em'>Total Comparison Errors
                </td>
                <td class='font-0dot75em'><%=@stats[:stats_total_ei_errors]%></td>
              </tr>
              <tr id="stats-ce">
                <td class='font-0dot75em'>
	<!--
                <p>Comparison Errors (not including "clics and coga empty values")</p>
	// -->
                <p>Comparison Errors</p>
                </td>
                <td class='font-0dot75em'><%=@stats[:stats_total_errors_no_0_5]%></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <div class="card border-0">
        <div class="card-body m-0 p-1">
          <table class="table table-bordered table-sm">
            <thead class="table-warning">
              <tr>
                <th class='font-0dot75em'>Error</th>
                <th class='font-0dot75em'>Count</th>
              </tr>
            </thead>
            <tbody class="cell-break">
              <tr id="stats-te1">
                <td class='font-0dot75em'><%=@error_hash[1]%></td>
                <td class='font-0dot75em'><%=@stats[:stats_total_errors1]%></td>
              </tr>
              <tr id="stats-te2">
                <td class='font-0dot75em'><%=@error_hash[2]%></td>
                <td class='font-0dot75em'><%=@stats[:stats_total_errors2]%></td>
              </tr>
              <tr id="stats-te3">
                <td class='font-0dot75em'><%=@error_hash[3]%></td>
                <td class='font-0dot75em'><%=@stats[:stats_total_errors3]%></td>
              </tr>
              <tr id="stats-te4">
                <td class='font-0dot75em'><%=@error_hash[4]%></td>
                <td class='font-0dot75em'><%=@stats[:stats_total_errors4]%></td>
              </tr>
	<!--
              <tr id="stats-te5">
                <td class='font-0dot75em'><%=@error_hash[5]%></td>
                <td class='font-0dot75em'><%=@stats[:stats_total_errors5]%></td>
              </tr>
	// -->
            </tbody>
          </table>
        </div>
      </div>
      <div class="card border-0">
        <div class="card-body m-0 p-1">
          <table class="table table-bordered table-sm">
            <thead class="table-warning">
              <tr>
                <th class='font-0dot75em'>Error</th>
                <th class='font-0dot75em'>Count</th>
              </tr>
            </thead>
            <tbody class="cell-break">

              <tr id="stats-te6">
                <td class='font-0dot75em'><%=@error_hash[6]%></td>
                <td class='font-0dot75em'><%=@stats[:stats_total_errors6]%></td>
              </tr>
              <tr id="stats-te7">
                <td class='font-0dot75em'><%=@error_hash[7]%></td>
                <td class='font-0dot75em'><%=@stats[:stats_total_errors7]%></td>
              </tr>
              <tr id="stats-te8">
                <td class='font-0dot75em'><%=@error_hash[8]%></td>
                <td class='font-0dot75em'><%=@stats[:stats_total_errors8]%></td>
              </tr>
              <tr id="stats-te9">
                <td class='font-0dot75em'><%=@error_hash[9]%></td>
                <td class='font-0dot75em'><%=@stats[:stats_total_errors9]%></td>
              </tr>
              <tr id="stats-te10">
                <td class='font-0dot75em'><%=@error_hash[10]%></td>
                <td class='font-0dot75em'><%=@stats[:stats_total_errors10]%></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  <% end %>
</div>