config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'reports#index'

  resources :reports, only: :index

  resources :reports, only: :show do
    get 'stats', to: 'reports#stats'
    get 'filtered', to: 'reports#filtered'
    get 'filtered_ee', to: 'reports#filtered_ee'
    get 'filtered_ei', to: 'reports#filtered_ei'
  end

  scope module: :reports do
    get 'download_committee_ei', to: 'downloads#download_committee_ei', param: :report_id
    get 'download_committee_ee', to: 'downloads#download_committee_ee', param: :report_id
  end

end

app/views/layouts/_navigation.html.erb
<ul class="nav nav-tabs font-1em">
  <li class="nav-item">
    <%= link_to "All Reports", reports_path, class:"nav-link" %>
  </li>

  <% if @recent_report %>
    <li class="nav-item">
      <%= link_to "Most Recent Report", report_path(@recent_report.id), class:"nav-link" %>
    </li>
  <%end %>

  <% if @current_page %>
    <li class="nav-item">
      <%= link_to @current_page, '', class:"nav-link" %>
    </li>
  <%end %>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CogarReports</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% flash.each do |type, msg| %>
      <div class="alert alert-info">
        <%= msg %>
      </div>
    <% end %>

    <div class="m-2">
      <%= render 'layouts/navigation' %>
    </div>

    <div class="m-2">
      <%= yield %>
    </div>

  </body>
</html>